### PR TITLE
Changing from Google form sign-up to new E&S MS forms

### PR DESCRIPTION
**Pull request by kallewesterling**

### CODE REVIEW

**Comment by kallewesterling** [comment]
@cassgvp Just wanted to make sure you see this!

**Comment by kallewesterling** [comment]
@davidwilby Do you have any idea why the tests fail here? We haven't edited anything but the documentation :/

**Comment by tom-andersson** [comment]
The failing tests are unrelated to this PR, so feel free to merge. I have opened an issue for the failing tests: https://github.com/alan-turing-institute/deepsensor/issues/115. Just make sure to handle any remaining requests on the Google form before the switch is made please!

Hint: @cassgvp ‘rebase and merge’ rather than closing the PR! :-)

**Comment by kallewesterling** [comment]
Thank you @tom-andersson !!

**Pull request merged**
